### ISSUE TITLE
Love the idea, but it just doesn't work

### ISSUE THREAD

**Issue by MattHulse** [vipzhicheng/logseq-plugin-title-bar#1]
I don't get any errors, but I also don't see anything in my title bar.  I've restarted logseq since installing the plugin and I still get nothing.  Is this meant to work with the latest version of logseq?

**Comment by vipzhicheng** [comment]
Yes, I notice that, Please wait sometime. there is a PR about this issue, wait this to be merged. https://github.com/logseq/marketplace/pull/524

**Comment by vipzhicheng** [comment]
Before the marketplace updated, you can manually make it work.

![image](https://github.com/vipzhicheng/logseq-plugin-title-bar/assets/1209538/da1a0d45-bbc6-441e-b5a3-f61a1fd3f8b2)

Edit package.json. change to `effect: true`
